In [264]:
import json
import pandas as pd

# Part 1: Reading and investigating data

Open up the `player_data.json` and investigate the data structure.

In [265]:
#list of players (with dict, with empty cells)
f = open('player_data.json')
data = json.load(f)

In [266]:
data[0]

{'PERSON_ID': 203518,
 'FIRST_NAME': 'Alex',
 'LAST_NAME': 'Abrines',
 'DISPLAY_FIRST_LAST': 'Alex Abrines',
 'DISPLAY_LAST_COMMA_FIRST': 'Abrines, Alex',
 'DISPLAY_FI_LAST': 'A. Abrines',
 'BIRTHDATE': '1993-08-01T00:00:00',
 'SCHOOL': ' ',
 'COUNTRY': 'Spain',
 'LAST_AFFILIATION': 'Spain/Spain',
 'HEIGHT': '',
 'WEIGHT': '',
 'SEASON_EXP': 2,
 'JERSEY': '',
 'POSITION': '',
 'ROSTERSTATUS': 'Inactive',
 'TEAM_ID': 0,
 'TEAM_NAME': '',
 'TEAM_ABBREVIATION': '',
 'TEAM_CODE': '',
 'TEAM_CITY': '',
 'PLAYERCODE': 'alex_abrines',
 'FROM_YEAR': 2016,
 'TO_YEAR': 2018,
 'DLEAGUE_FLAG': 'N',
 'NBA_FLAG': 'Y',
 'GAMES_PLAYED_FLAG': 'Y',
 'DRAFT_YEAR': '2013',
 'DRAFT_ROUND': '2',
 'DRAFT_NUMBER': '32',
 'CAREER_STATS': {'PTS': 5.3,
  'AST': 0.5,
  'REB': 1.4,
  'ALL_STAR_APPEARANCES': 0},
 'GAMELOG': [{'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800772',
   'GAME_DATE': 'FEB 01, 2019',
   'MATCHUP': 'OKC @ MIA',
   'WL': 'W',
   'MIN': 9,
   'FGM': 0,
   'FGA': 2,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 1,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 0,
   'REB': 0,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 1,
   'PTS': 0,
   'PLUS_MINUS': -8,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800751',
   'GAME_DATE': 'JAN 29, 2019',
   'MATCHUP': 'OKC @ ORL',
   'WL': 'W',
   'MIN': 6,
   'FGM': 1,
   'FGA': 2,
   'FG_PCT': 0.5,
   'FG3M': 1,
   'FG3A': 2,
   'FG3_PCT': 0.5,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 1,
   'PTS': 3,
   'PLUS_MINUS': 4,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800493',
   'GAME_DATE': 'DEC 23, 2018',
   'MATCHUP': 'OKC vs. MIN',
   'WL': 'L',
   'MIN': 27,
   'FGM': 2,
   'FGA': 6,
   'FG_PCT': 0.333,
   'FG3M': 1,
   'FG3A': 5,
   'FG3_PCT': 0.2,
   'FTM': 2,
   'FTA': 2,
   'FT_PCT': 1.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 0,
   'STL': 0,
   'BLK': 2,
   'TOV': 0,
   'PF': 2,
   'PTS': 7,
   'PLUS_MINUS': 1,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800485',
   'GAME_DATE': 'DEC 22, 2018',
   'MATCHUP': 'OKC @ UTA',
   'WL': 'W',
   'MIN': 16,
   'FGM': 2,
   'FGA': 4,
   'FG_PCT': 0.5,
   'FG3M': 2,
   'FG3A': 4,
   'FG3_PCT': 0.5,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 4,
   'PTS': 6,
   'PLUS_MINUS': 13,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800466',
   'GAME_DATE': 'DEC 19, 2018',
   'MATCHUP': 'OKC @ SAC',
   'WL': 'W',
   'MIN': 23,
   'FGM': 3,
   'FGA': 7,
   'FG_PCT': 0.429,
   'FG3M': 3,
   'FG3A': 7,
   'FG3_PCT': 0.429,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 1,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 4,
   'PTS': 9,
   'PLUS_MINUS': 6,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800447',
   'GAME_DATE': 'DEC 17, 2018',
   'MATCHUP': 'OKC vs. CHI',
   'WL': 'W',
   'MIN': 14,
   'FGM': 3,
   'FGA': 4,
   'FG_PCT': 0.75,
   'FG3M': 2,
   'FG3A': 3,
   'FG3_PCT': 0.667,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 2,
   'DREB': 1,
   'REB': 3,
   'AST': 0,
   'STL': 1,
   'BLK': 0,
   'TOV': 0,
   'PF': 1,
   'PTS': 8,
   'PLUS_MINUS': 4,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800434',
   'GAME_DATE': 'DEC 15, 2018',
   'MATCHUP': 'OKC vs. LAC',
   'WL': 'W',
   'MIN': 20,
   'FGM': 2,
   'FGA': 4,
   'FG_PCT': 0.5,
   'FG3M': 0,
   'FG3A': 2,
   'FG3_PCT': 0.0,
   'FTM': 2,
   'FTA': 2,
   'FT_PCT': 1.0,
   'OREB': 0,
   'DREB': 4,
   'REB': 4,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 0,
   'PTS': 6,
   'PLUS_MINUS': 7,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800426',
   'GAME_DATE': 'DEC 14, 2018',
   'MATCHUP': 'OKC @ DEN',
   'WL': 'L',
   'MIN': 19,
   'FGM': 0,
   'FGA': 1,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 1,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 0,
   'REB': 0,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 1,
   'PF': 0,
   'PTS': 0,
   'PLUS_MINUS': -1,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800411',
   'GAME_DATE': 'DEC 12, 2018',
   'MATCHUP': 'OKC @ NOP',
   'WL': 'L',
   'MIN': 14,
   'FGM': 2,
   'FGA': 6,
   'FG_PCT': 0.333,
   'FG3M': 1,
   'FG3A': 5,
   'FG3_PCT': 0.2,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 2,
   'STL': 1,
   'BLK': 0,
   'TOV': 0,
   'PF': 0,
   'PTS': 5,
   'PLUS_MINUS': 0,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800396',
   'GAME_DATE': 'DEC 10, 2018',
   'MATCHUP': 'OKC vs. UTA',
   'WL': 'W',
   'MIN': 19,
   'FGM': 0,
   'FGA': 2,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 1,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 3,
   'REB': 3,
   'AST': 0,
   'STL': 1,
   'BLK': 0,
   'TOV': 2,
   'PF': 1,
   'PTS': 0,
   'PLUS_MINUS': -12,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800373',
   'GAME_DATE': 'DEC 07, 2018',
   'MATCHUP': 'OKC @ CHI',
   'WL': 'L',
   'MIN': 15,
   'FGM': 1,
   'FGA': 4,
   'FG_PCT': 0.25,
   'FG3M': 1,
   'FG3A': 4,
   'FG3_PCT': 0.25,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 3,
   'REB': 3,
   'AST': 1,
   'STL': 0,
   'BLK': 0,
   'TOV': 1,
   'PF': 3,
   'PTS': 3,
   'PLUS_MINUS': -15,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800358',
   'GAME_DATE': 'DEC 05, 2018',
   'MATCHUP': 'OKC @ BKN',
   'WL': 'W',
   'MIN': 19,
   'FGM': 0,
   'FGA': 2,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 2,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 1,
   'STL': 3,
   'BLK': 0,
   'TOV': 1,
   'PF': 1,
   'PTS': 0,
   'PLUS_MINUS': -10,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800343',
   'GAME_DATE': 'DEC 03, 2018',
   'MATCHUP': 'OKC @ DET',
   'WL': 'W',
   'MIN': 18,
   'FGM': 1,
   'FGA': 3,
   'FG_PCT': 0.333,
   'FG3M': 0,
   'FG3A': 2,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 1,
   'STL': 0,
   'BLK': 0,
   'TOV': 1,
   'PF': 1,
   'PTS': 2,
   'PLUS_MINUS': -1,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800325',
   'GAME_DATE': 'NOV 30, 2018',
   'MATCHUP': 'OKC vs. ATL',
   'WL': 'W',
   'MIN': 26,
   'FGM': 7,
   'FGA': 11,
   'FG_PCT': 0.636,
   'FG3M': 7,
   'FG3A': 11,
   'FG3_PCT': 0.636,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 2,
   'REB': 2,
   'AST': 1,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 2,
   'PTS': 21,
   'PLUS_MINUS': 6,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800313',
   'GAME_DATE': 'NOV 28, 2018',
   'MATCHUP': 'OKC vs. CLE',
   'WL': 'W',
   'MIN': 27,
   'FGM': 1,
   'FGA': 9,
   'FG_PCT': 0.111,
   'FG3M': 1,
   'FG3A': 8,
   'FG3_PCT': 0.125,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 1,
   'DREB': 2,
   'REB': 3,
   'AST': 1,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 1,
   'PTS': 3,
   'PLUS_MINUS': 13,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800282',
   'GAME_DATE': 'NOV 24, 2018',
   'MATCHUP': 'OKC vs. DEN',
   'WL': 'L',
   'MIN': 8,
   'FGM': 0,
   'FGA': 2,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 2,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 1,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 1,
   'PTS': 0,
   'PLUS_MINUS': -9,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800274',
   'GAME_DATE': 'NOV 23, 2018',
   'MATCHUP': 'OKC vs. CHA',
   'WL': 'W',
   'MIN': 7,
   'FGM': 0,
   'FGA': 1,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 1,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 0,
   'REB': 0,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 4,
   'PTS': 0,
   'PLUS_MINUS': 1,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800209',
   'GAME_DATE': 'NOV 14, 2018',
   'MATCHUP': 'OKC vs. NYK',
   'WL': 'W',
   'MIN': 7,
   'FGM': 0,
   'FGA': 2,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 1,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 0,
   'REB': 0,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 1,
   'PF': 0,
   'PTS': 0,
   'PLUS_MINUS': 3,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800196',
   'GAME_DATE': 'NOV 12, 2018',
   'MATCHUP': 'OKC vs. PHX',
   'WL': 'W',
   'MIN': 20,
   'FGM': 2,
   'FGA': 6,
   'FG_PCT': 0.333,
   'FG3M': 2,
   'FG3A': 6,
   'FG3_PCT': 0.333,
   'FTM': 2,
   'FTA': 2,
   'FT_PCT': 1.0,
   'OREB': 0,
   'DREB': 2,
   'REB': 2,
   'AST': 2,
   'STL': 2,
   'BLK': 1,
   'TOV': 1,
   'PF': 4,
   'PTS': 8,
   'PLUS_MINUS': -11,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800181',
   'GAME_DATE': 'NOV 10, 2018',
   'MATCHUP': 'OKC @ DAL',
   'WL': 'L',
   'MIN': 26,
   'FGM': 2,
   'FGA': 6,
   'FG_PCT': 0.333,
   'FG3M': 2,
   'FG3A': 4,
   'FG3_PCT': 0.5,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 2,
   'REB': 2,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 1,
   'PF': 2,
   'PTS': 6,
   'PLUS_MINUS': -9,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800163',
   'GAME_DATE': 'NOV 08, 2018',
   'MATCHUP': 'OKC vs. HOU',
   'WL': 'W',
   'MIN': 19,
   'FGM': 0,
   'FGA': 3,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 3,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 1,
   'DREB': 3,
   'REB': 4,
   'AST': 0,
   'STL': 1,
   'BLK': 0,
   'TOV': 1,
   'PF': 0,
   'PTS': 0,
   'PLUS_MINUS': -8,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800153',
   'GAME_DATE': 'NOV 07, 2018',
   'MATCHUP': 'OKC @ CLE',
   'WL': 'W',
   'MIN': 26,
   'FGM': 3,
   'FGA': 12,
   'FG_PCT': 0.25,
   'FG3M': 3,
   'FG3A': 10,
   'FG3_PCT': 0.3,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 0,
   'REB': 0,
   'AST': 0,
   'STL': 1,
   'BLK': 0,
   'TOV': 0,
   'PF': 1,
   'PTS': 9,
   'PLUS_MINUS': 11,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800144',
   'GAME_DATE': 'NOV 05, 2018',
   'MATCHUP': 'OKC vs. NOP',
   'WL': 'W',
   'MIN': 30,
   'FGM': 2,
   'FGA': 4,
   'FG_PCT': 0.5,
   'FG3M': 1,
   'FG3A': 2,
   'FG3_PCT': 0.5,
   'FTM': 2,
   'FTA': 2,
   'FT_PCT': 1.0,
   'OREB': 0,
   'DREB': 4,
   'REB': 4,
   'AST': 3,
   'STL': 0,
   'BLK': 0,
   'TOV': 1,
   'PF': 1,
   'PTS': 7,
   'PLUS_MINUS': 6,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800119',
   'GAME_DATE': 'NOV 02, 2018',
   'MATCHUP': 'OKC @ WAS',
   'WL': 'W',
   'MIN': 24,
   'FGM': 3,
   'FGA': 8,
   'FG_PCT': 0.375,
   'FG3M': 2,
   'FG3A': 7,
   'FG3_PCT': 0.286,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 2,
   'STL': 0,
   'BLK': 2,
   'TOV': 0,
   'PF': 3,
   'PTS': 8,
   'PLUS_MINUS': 27,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800111',
   'GAME_DATE': 'NOV 01, 2018',
   'MATCHUP': 'OKC @ CHA',
   'WL': 'W',
   'MIN': 30,
   'FGM': 9,
   'FGA': 15,
   'FG_PCT': 0.6,
   'FG3M': 5,
   'FG3A': 10,
   'FG3_PCT': 0.5,
   'FTM': 2,
   'FTA': 2,
   'FT_PCT': 1.0,
   'OREB': 0,
   'DREB': 2,
   'REB': 2,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 4,
   'PTS': 25,
   'PLUS_MINUS': 16,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800103',
   'GAME_DATE': 'OCT 30, 2018',
   'MATCHUP': 'OKC vs. LAC',
   'WL': 'W',
   'MIN': 15,
   'FGM': 1,
   'FGA': 2,
   'FG_PCT': 0.5,
   'FG3M': 1,
   'FG3A': 1,
   'FG3_PCT': 1.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 0,
   'REB': 0,
   'AST': 0,
   'STL': 4,
   'BLK': 1,
   'TOV': 1,
   'PF': 5,
   'PTS': 3,
   'PLUS_MINUS': -1,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800085',
   'GAME_DATE': 'OCT 28, 2018',
   'MATCHUP': 'OKC vs. PHX',
   'WL': 'W',
   'MIN': 24,
   'FGM': 0,
   'FGA': 5,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 3,
   'FG3_PCT': 0.0,
   'FTM': 2,
   'FTA': 2,
   'FT_PCT': 1.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 0,
   'STL': 2,
   'BLK': 0,
   'TOV': 0,
   'PF': 2,
   'PTS': 2,
   'PLUS_MINUS': -1,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800065',
   'GAME_DATE': 'OCT 25, 2018',
   'MATCHUP': 'OKC vs. BOS',
   'WL': 'L',
   'MIN': 19,
   'FGM': 2,
   'FGA': 5,
   'FG_PCT': 0.4,
   'FG3M': 2,
   'FG3A': 5,
   'FG3_PCT': 0.4,
   'FTM': 0,
   'FTA': 1,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 1,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 2,
   'PTS': 6,
   'PLUS_MINUS': 6,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800037',
   'GAME_DATE': 'OCT 21, 2018',
   'MATCHUP': 'OKC vs. SAC',
   'WL': 'L',
   'MIN': 5,
   'FGM': 0,
   'FGA': 1,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 1,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 2,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 0,
   'PTS': 0,
   'PLUS_MINUS': 5,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800025',
   'GAME_DATE': 'OCT 19, 2018',
   'MATCHUP': 'OKC @ LAC',
   'WL': 'L',
   'MIN': 32,
   'FGM': 4,
   'FGA': 10,
   'FG_PCT': 0.4,
   'FG3M': 2,
   'FG3A': 7,
   'FG3_PCT': 0.286,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 1,
   'DREB': 1,
   'REB': 2,
   'AST': 1,
   'STL': 1,
   'BLK': 0,
   'TOV': 2,
   'PF': 0,
   'PTS': 10,
   'PLUS_MINUS': -9,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800002',
   'GAME_DATE': 'OCT 16, 2018',
   'MATCHUP': 'OKC @ GSW',
   'WL': 'L',
   'MIN': 23,
   'FGM': 3,
   'FGA': 8,
   'FG_PCT': 0.375,
   'FG3M': 2,
   'FG3A': 6,
   'FG3_PCT': 0.333,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 2,
   'REB': 2,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 2,
   'PTS': 8,
   'PLUS_MINUS': -5,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760}]}

In [101]:
len(data)

538

In [267]:
data[0].keys()

dict_keys(['PERSON_ID', 'FIRST_NAME', 'LAST_NAME', 'DISPLAY_FIRST_LAST', 'DISPLAY_LAST_COMMA_FIRST', 'DISPLAY_FI_LAST', 'BIRTHDATE', 'SCHOOL', 'COUNTRY', 'LAST_AFFILIATION', 'HEIGHT', 'WEIGHT', 'SEASON_EXP', 'JERSEY', 'POSITION', 'ROSTERSTATUS', 'TEAM_ID', 'TEAM_NAME', 'TEAM_ABBREVIATION', 'TEAM_CODE', 'TEAM_CITY', 'PLAYERCODE', 'FROM_YEAR', 'TO_YEAR', 'DLEAGUE_FLAG', 'NBA_FLAG', 'GAMES_PLAYED_FLAG', 'DRAFT_YEAR', 'DRAFT_ROUND', 'DRAFT_NUMBER', 'CAREER_STATS', 'GAMELOG'])

In [268]:
print(len(data[537]['GAMELOG']))
for i in data[537]['GAMELOG']:
    print(i['Game_ID'], '\n')

59
0021801229

0021801205

0021801192

0021801176

0021801151

0021801136

0021801127

0021801112

0021801095

0021801081

0021801064

0021801049

0021801033

0021801013

0021801006

0021800985

0021800958

0021800947

0021800933

0021800919

0021800907

0021800895

0021800879

0021800863

0021800845

0021800829

0021800798

0021800782

0021800769

0021800755

0021800743

0021800719

0021800701

0021800686

0021800670

0021800656

0021800644

0021800627

0021800616

0021800596

0021800585

0021800574

0021800562

0021800526

0021800514

0021800500

0021800496

0021800478

0021800453

0021800439

0021800430

0021800384

0021800337

0021800304

0021800183

0021800139

0021800132

0021800060

0021800048

In [ ]:
# Final Dataframe --> w/player info --> w/ gamelogs --> merge the two

In [269]:
df = pd.DataFrame()

for person in data:
    if len(person['GAMELOG']) == 0:
        continue
    df1 = pd.DataFrame(person, columns=['DISPLAY_FIRST_LAST', 'PERSON_ID', 'TEAM_ID'], index=[0])
    df2 = pd.DataFrame(person['GAMELOG'])
    merged = pd.merge(df1, df2, left_on='PERSON_ID', right_on='Player_ID', how='outer')
    df = pd.concat([df, merged])
    
df.reset_index(drop=True, inplace=True)

In [270]:
df.head(10)

,DISPLAY_FIRST_LAST,PERSON_ID,TEAM_ID_x,AST,BLK,DREB,FG3A,FG3M,FG3_PCT,FGA,...,PTS,Player_ID,REB,SEASON_ID,STL,TEAM_ABBREVIATION,TEAM_ID_y,TOV,VIDEO_AVAILABLE,WL
0,Alex Abrines,203518,0,0,0,0,1,0,0.000,2,...,0,203518,0,22018,0,OKC,1610612760,0,1,W
1,Alex Abrines,203518,0,0,0,1,2,1,0.500,2,...,3,203518,1,22018,0,OKC,1610612760,0,1,W
2,Alex Abrines,203518,0,0,2,1,5,1,0.200,6,...,7,203518,1,22018,0,OKC,1610612760,0,1,L
3,Alex Abrines,203518,0,0,0,1,4,2,0.500,4,...,6,203518,1,22018,0,OKC,1610612760,0,1,W
4,Alex Abrines,203518,0,1,0,1,7,3,0.429,7,...,9,203518,1,22018,0,OKC,1610612760,0,1,W
5,Alex Abrines,203518,0,0,0,1,3,2,0.667,4,...,8,203518,3,22018,1,OKC,1610612760,0,1,W
6,Alex Abrines,203518,0,0,0,4,2,0,0.000,4,...,6,203518,4,22018,0,OKC,1610612760,0,1,W
7,Alex Abrines,203518,0,0,0,0,1,0,0.000,1,...,0,203518,0,22018,0,OKC,1610612760,1,1,L
8,Alex Abrines,203518,0,2,0,1,5,1,0.200,6,...,5,203518,1,22018,1,OKC,1610612760,0,1,L
9,Alex Abrines,203518,0,0,0,3,1,0,0.000,2,...,0,203518,3,22018,1,OKC,1610612760,2,1,W

In [271]:
print(len(df))
df.columns

26101

Index(['DISPLAY_FIRST_LAST', 'PERSON_ID', 'TEAM_ID_x', 'AST', 'BLK', 'DREB',
       'FG3A', 'FG3M', 'FG3_PCT', 'FGA', 'FGM', 'FG_PCT', 'FTA', 'FTM',
       'FT_PCT', 'GAME_DATE', 'Game_ID', 'MATCHUP', 'MIN', 'OREB', 'PF',
       'PLUS_MINUS', 'PTS', 'Player_ID', 'REB', 'SEASON_ID', 'STL',
       'TEAM_ABBREVIATION', 'TEAM_ID_y', 'TOV', 'VIDEO_AVAILABLE', 'WL'],
      dtype='object')

# Part 2:  Creating the Dataframe

Create a data frame where each row corresponds to a __game__ for each player. You must have at least the following columns in your final dataframe:

'DISPLAY_FIRST_LAST', 'PERSON_ID', 'TEAM_ID', 'AST', 'BLK', 'Game_ID',  'MIN', 'PTS', 'REB', 'STL', 'TEAM_ABBREVIATION'

*You can include additional columns in your dataframe, so you don't have to do additional work to remove other columns.*

In [ ]:
print(df.DISPLAY_FIRST_LAST[df['PTS']==df['PTS'].max()], '\n')

# Part 3: Pandas Questions

Answer the following questions

## 1 
- Find the player who scored the most points in an individual game last season.

-  Now do the same for rebounds, blocks, and assists.

In [272]:
# Nabil's answer
df[df['PTS'] == df['PTS'].max()]

,DISPLAY_FIRST_LAST,PERSON_ID,TEAM_ID_x,AST,BLK,DREB,FG3A,FG3M,FG3_PCT,FGA,...,PTS,Player_ID,REB,SEASON_ID,STL,TEAM_ABBREVIATION,TEAM_ID_y,TOV,VIDEO_AVAILABLE,WL
10323,James Harden,201935,1610612745,1,0,5,13,9,0.692,34,...,61,201935,7,22018,3,HOU,1610612745,3,1,W
10348,James Harden,201935,1610612745,4,0,9,20,5,0.250,38,...,61,201935,15,22018,5,HOU,1610612745,5,1,W

In [274]:
# returns the index
df['PTS'].idxmax()

10323

In [289]:
# returns index
df['PTS'].nlargest(1, keep = 'all')

10323    61
10348    61
Name: PTS, dtype: int64

In [273]:
# Sean's answer
df.loc[df['PTS'].idxmax()]

DISPLAY_FIRST_LAST    James Harden
PERSON_ID                   201935
TEAM_ID_x               1610612745
AST                              1
BLK                              0
DREB                             5
FG3A                            13
FG3M                             9
FG3_PCT                      0.692
FGA                             34
FGM                             19
FG_PCT                       0.559
FTA                             17
FTM                             14
FT_PCT                       0.824
GAME_DATE             MAR 22, 2019
Game_ID                 0021801084
MATCHUP                HOU vs. SAS
MIN                             37
OREB                             2
PF                               3
PLUS_MINUS                      18
PTS                             61
Player_ID                   201935
REB                              7
SEASON_ID                    22018
STL                              3
TEAM_ABBREVIATION              HOU
TEAM_ID_y               1610612745
TOV                              3
VIDEO_AVAILABLE                  1
WL                               W
Name: 10323, dtype: object

In [129]:
print(df.DISPLAY_FIRST_LAST[df['PTS']==df['PTS'].max()], '\n')
print(df.DISPLAY_FIRST_LAST[df['REB']==df['REB'].max()], '\n')
print(df.DISPLAY_FIRST_LAST[df['BLK']==df['BLK'].max()], '\n')
print(df.DISPLAY_FIRST_LAST[df['AST']==df['AST'].max()], '\n')

10323    James Harden
10348    James Harden
Name: DISPLAY_FIRST_LAST, dtype: object

23773    Karl-Anthony Towns
Name: DISPLAY_FIRST_LAST, dtype: object

21109    Mitchell Robinson
25135     Hassan Whiteside
Name: DISPLAY_FIRST_LAST, dtype: object

24969    Russell Westbrook
Name: DISPLAY_FIRST_LAST, dtype: object

## 2: 

- Find the player who scored the most points for the entire season.

- Now do the same for rebounds, blocks, and assists.

In [278]:
# Xristos's answer
df.groupby('DISPLAY_FIRST_LAST')['PTS'].sum().sort_values(ascending=False).head(1)

DISPLAY_FIRST_LAST
James Harden    2818
Name: PTS, dtype: int64

In [279]:
# Sean's code
grouped = df.groupby('DISPLAY_FIRST_LAST').sum()
player = grouped['AST'].idxmax()
print(player)
grouped.loc[player]['AST']

Russell Westbrook

784.0

In [276]:
print(df.DISPLAY_FIRST_LAST[df['PTS']==df['PTS'].max()], '\n')

10323    James Harden
10348    James Harden
Name: DISPLAY_FIRST_LAST, dtype: object

In [ ]:
df.nunique()

In [200]:
df.tail()

,DISPLAY_FIRST_LAST,PERSON_ID,TEAM_ID_x,AST,BLK,DREB,FG3A,FG3M,FG3_PCT,FGA,...,Player_ID,REB,SEASON_ID,STL,TEAM_ABBREVIATION,TEAM_ID_y,TOV,VIDEO_AVAILABLE,WL,Total Pts
26097,Ivica Zubac,1627826,1610612746,1,0,4,0,0,0.0,3,...,1627826,6,22018,0,LAL,1610612747,1,1,L,547146
26098,Ivica Zubac,1627826,1610612746,0,0,4,0,0,0.0,5,...,1627826,8,22018,1,LAL,1610612747,2,1,W,547146
26099,Ivica Zubac,1627826,1610612746,1,0,1,0,0,0.0,1,...,1627826,2,22018,0,LAL,1610612747,0,1,W,547146
26100,Ivica Zubac,1627826,1610612746,0,1,0,0,0,0.0,1,...,1627826,1,22018,0,LAL,1610612747,0,1,L,547146
Total Pts,273573,273573,273573,273573,273573,273573,273573,273573,273573.0,273573,...,273573,273573,273573,273573,273573,273573,273573,273573,273573,547146

In [260]:
plsyer_grouped

KeyError: 'DISPLAY_FIRST_LAST'

In [282]:
#df.loc['Total'] = pd.Series(df['MyColumn'].sum(), index = ['MyColumn'])
players_grouped = df.groupby(['DISPLAY_FIRST_LAST'])
players_grouped

In [146]:
# df['Total Pts'] = df['PTS'].groupby('DISPLAY_FIRST_LAST').sum()
print(df['DISPLAY_FIRST_LAST'][df['Total Pts']==df['Total Pts'].max()], '\n')

KeyError: 'DISPLAY_FIRST_LAST'

In [205]:
df.tail(10)

,DISPLAY_FIRST_LAST,PERSON_ID,TEAM_ID_x,AST,BLK,DREB,FG3A,FG3M,FG3_PCT,FGA,...,PTS,Player_ID,REB,SEASON_ID,STL,TEAM_ABBREVIATION,TEAM_ID_y,TOV,VIDEO_AVAILABLE,WL
26091,Ivica Zubac,1627826,1610612746,1,0,2,0,0,0.0,2,...,4,1627826,2,22018,0,LAL,1610612747,0,1,L
26092,Ivica Zubac,1627826,1610612746,0,0,1,0,0,0.0,4,...,6,1627826,1,22018,0,LAL,1610612747,0,1,W
26093,Ivica Zubac,1627826,1610612746,0,1,2,0,0,0.0,0,...,0,1627826,2,22018,0,LAL,1610612747,0,1,W
26094,Ivica Zubac,1627826,1610612746,0,0,1,0,0,0.0,0,...,0,1627826,1,22018,0,LAL,1610612747,0,1,W
26095,Ivica Zubac,1627826,1610612746,0,1,1,0,0,0.0,2,...,0,1627826,2,22018,0,LAL,1610612747,1,1,L
26096,Ivica Zubac,1627826,1610612746,0,0,1,0,0,0.0,2,...,0,1627826,2,22018,0,LAL,1610612747,0,1,W
26097,Ivica Zubac,1627826,1610612746,1,0,4,0,0,0.0,3,...,5,1627826,6,22018,0,LAL,1610612747,1,1,L
26098,Ivica Zubac,1627826,1610612746,0,0,4,0,0,0.0,5,...,9,1627826,8,22018,1,LAL,1610612747,2,1,W
26099,Ivica Zubac,1627826,1610612746,1,0,1,0,0,0.0,1,...,0,1627826,2,22018,0,LAL,1610612747,0,1,W
26100,Ivica Zubac,1627826,1610612746,0,1,0,0,0,0.0,1,...,0,1627826,1,22018,0,LAL,1610612747,0,1,L

## 3:
How many players played in at least 82 games last season?

In [286]:
df['DISPLAY_FIRST_LAST'].value_counts()

Cory Joseph                 82
DeAndre' Bembry             82
Bam Adebayo                 82
Patty Mills                 82
Monte Morris                82
Buddy Hield                 82
Reggie Jackson              82
Kemba Walker                82
Mason Plumlee               82
Montrezl Harrell            82
Bryn Forbes                 82
Tobias Harris               82
Shai Gilgeous-Alexander     82
Joe Ingles                  82
Kentavious Caldwell-Pope    82
Bradley Beal                82
Collin Sexton               82
Royce O'Neale               82
Justin Holiday              82
PJ Tucker                   82
Mikal Bridges               82
De'Aaron Fox                81
Ed Davis                    81
Evan Fournier               81
Al-Farouq Aminu             81
Dorian Finney-Smith         81
Thaddeus Young              81
Bojan Bogdanovic            81
Ryan Arcidiacono            81
Rudy Gobert                 81
                            ..
Okaro White                  3
Ike Anigbogu                 3
Donatas Motiejunas           3
Gary Payton II               3
Donte Grantham               3
Tony Bradley                 3
Justin Patton                3
Emanuel Terry                3
Trevon Duval                 3
Isaiah Hicks                 3
Yante Maten                  2
Dusty Hannahs                2
Kostas Antetokounmpo         2
Terrence Jones               2
Vincent Edwards              2
J.P. Macura                  2
Angel Delgado                2
RJ Hunter                    1
Joe Chealey                  1
Tahjere McCall               1
Zach Lofton                  1
Kobi Simmons                 1
Tyler Ulis                   1
Tyler Davis                  1
Zhou Qi                      1
DJ Stephens                  1
Kalin Lucas                  1
Jordan Sibert                1
John Holland                 1
George King                  1
Name: DISPLAY_FIRST_LAST, Length: 530, dtype: int64

In [284]:
# Warren's code
(df['DISPLAY_FIRST_LAST'].value_counts()>=82).sum()

21

In [287]:
games = df.groupby('DISPLAY_FIRST_LAST')['AST'].count()
len(games[games>=82])

21

In [218]:
df.tail()

,DISPLAY_FIRST_LAST,PERSON_ID,TEAM_ID_x,AST,BLK,DREB,FG3A,FG3M,FG3_PCT,FGA,...,PTS,Player_ID,REB,SEASON_ID,STL,TEAM_ABBREVIATION,TEAM_ID_y,TOV,VIDEO_AVAILABLE,WL
26096,Ivica Zubac,1627826,1610612746,0,0,1,0,0,0.0,2,...,0,1627826,2,22018,0,LAL,1610612747,0,1,W
26097,Ivica Zubac,1627826,1610612746,1,0,4,0,0,0.0,3,...,5,1627826,6,22018,0,LAL,1610612747,1,1,L
26098,Ivica Zubac,1627826,1610612746,0,0,4,0,0,0.0,5,...,9,1627826,8,22018,1,LAL,1610612747,2,1,W
26099,Ivica Zubac,1627826,1610612746,1,0,1,0,0,0.0,1,...,0,1627826,2,22018,0,LAL,1610612747,0,1,W
26100,Ivica Zubac,1627826,1610612746,0,1,0,0,0,0.0,1,...,0,1627826,1,22018,0,LAL,1610612747,0,1,L

In [172]:
df.groupby('DISPLAY_FIRST_LAST')['GAMES_PLAYED_FLAG'].count()

KeyError: 'Column not found: GAMES_PLAYED_FLAG'

## 4: 
- Find which team scored the most points for the entire season.

- Now do the same for rebounds, blocks, and assists.

In [288]:
# John's code
grouped_season = df.groupby(['SEASON_ID','TEAM_ABBREVIATION'])['PTS'].sum()
grouped_season.nlargest(1, keep = 'first')

SEASON_ID  TEAM_ABBREVIATION
22018      MIL                  9686
Name: PTS, dtype: int64

In [295]:
teams = df.groupby('TEAM_ABBREVIATION')
teams['PTS'].sum().idxmax()

'MIL'

In [220]:
print(df.groupby('TEAM_ABBREVIATION')['PTS'].sum())

TEAM_ABBREVIATION
ATL    9294
BKN    9204
BOS    9216
CHA    9081
CHI    8605
CLE    8567
DAL    8927
DEN    9075
DET    8778
GSW    9650
HOU    9341
IND    8857
LAC    9442
LAL    9165
MEM    8490
MIA    8668
MIL    9686
MIN    9223
NOP    9466
NYK    8575
OKC    9387
ORL    8800
PHI    9445
PHX    8815
POR    9402
SAC    9363
SAS    9156
TOR    9384
UTA    9161
WAS    9350
Name: PTS, dtype: int64

## 5:
Which team had the most players play for them last season?

In [292]:
#Brendan's code
n_players = df.groupby('TEAM_ABBREVIATION')['PERSON_ID'].nunique()
n_players.loc[n_players.apply(lambda x: x >= n_players.max())]

TEAM_ABBREVIATION
MEM    28
Name: PERSON_ID, dtype: int64

In [297]:
# Sean's code
teams['Player_ID'].nunique().idxmax()

'MEM'

## 6:
- How many players play for more than one team last year?

- What is the most number of teams a player played for last season?

In [299]:
# Sean's code
player_teams = df.groupby('DISPLAY_FIRST_LAST')['TEAM_ABBREVIATION']

In [306]:
# Sean's code
df.groupby('DISPLAY_FIRST_LAST')['TEAM_ABBREVIATION'].nunique().max()

3

In [300]:
multi_teams = player_teams.nunique()>1
multi_teams

DISPLAY_FIRST_LAST
Aaron Gordon           False
Aaron Holiday          False
Abdel Nader            False
Al Horford             False
Al-Farouq Aminu        False
Alan Williams          False
Alec Burks              True
Alex Abrines           False
Alex Caruso            False
Alex Len               False
Alex Poythress         False
Alfonzo McKinnie       False
Alize Johnson          False
Allen Crabbe           False
Allonzo Trier          False
Amile Jefferson        False
Amir Johnson           False
Andre Drummond         False
Andre Iguodala         False
Andre Ingram           False
Andrew Bogut           False
Andrew Harrison         True
Andrew Wiggins         False
Anfernee Simons        False
Angel Delgado          False
Ante Zizic             False
Anthony Davis          False
Anthony Tolliver       False
Antonio Blakeney       False
Aron Baynes            False
                       ...
Tyler Zeller            True
Tyreke Evans           False
Tyrone Wallace         False
Tyson Chandler          True
Tyus Jones             False
Udonis Haslem          False
Victor Oladipo         False
Vince Carter           False
Vincent Edwards        False
Wade Baldwin IV        False
Walter Lemon Jr.       False
Wayne Ellington         True
Wayne Selden            True
Wendell Carter Jr.     False
Wes Iwundu             False
Wesley Johnson          True
Wesley Matthews         True
Will Barton            False
Willie Cauley-Stein    False
Willy Hernangomez      False
Wilson Chandler         True
Yante Maten            False
Yogi Ferrell           False
Yuta Watanabe          False
Zach Collins           False
Zach LaVine            False
Zach Lofton            False
Zaza Pachulia          False
Zhaire Smith           False
Zhou Qi                False
Name: TEAM_ABBREVIATION, Length: 530, dtype: bool

In [302]:
df.groupby('TEAM_ABBREVIATION')['DISPLAY_FIRST_LAST'].value_counts()

TEAM_ABBREVIATION  DISPLAY_FIRST_LAST
ATL                DeAndre' Bembry       82
                   Trae Young            81
                   Alex Len              77
                   Vince Carter          76
                   Kevin Huerter         75
                   Kent Bazemore         67
                   Dewayne Dedmon        64
                   John Collins          61
                   Taurean Prince        55
                   Jeremy Lin            51
                   Justin Anderson       48
                   Omari Spellman        46
                   Jaylen Adams          34
                   Tyler Dorsey          27
                   Alex Poythress        21
                   Daniel Hamilton       19
                   Miles Plumlee         18
                   Deyonta Davis          9
                   BJ Johnson             6
                   Isaac Humphries        5
                   Tyler Zeller           2
                   Jordan Sibert          1
BKN                D'Angelo Russell      81
                   Ed Davis              81
                   Jarrett Allen         80
                   Joe Harris            76
                   Spencer Dinwiddie     68
                   DeMarre Carroll       67
                   Rodions Kurucs        63
                   Jared Dudley          59
                                         ..
UTA                Raul Neto             37
                   Alec Burks            17
                   Naz Mitrou-Long       14
                   Tyler Cavanaugh       11
                   Tony Bradley           3
WAS                Bradley Beal          82
                   Tomas Satoransky      80
                   Jeff Green            77
                   Thomas Bryant         72
                   Troy Brown Jr.        52
                   Chasson Randle        49
                   Trevor Ariza          43
                   Otto Porter Jr.       41
                   Sam Dekker            38
                   Ian Mahinmi           34
                   Markieff Morris       34
                   John Wall             32
                   Austin Rivers         29
                   Kelly Oubre Jr.       29
                   Bobby Portis          28
                   Jordan McRae          27
                   Jabari Parker         25
                   Jason Smith           12
                   Wesley Johnson        12
                   Dwight Howard          9
                   Devin Robinson         7
                   John Jenkins           4
                   Ron Baker              4
                   Gary Payton II         3
                   Okaro White            3
Name: DISPLAY_FIRST_LAST, Length: 622, dtype: int64

In [304]:
df.groupby('TEAM_ABBREVIATION')['DISPLAY_FIRST_LAST'].value_counts().unstack().fillna(0)#.astype(bool)

DISPLAY_FIRST_LAST,Aaron Gordon,Aaron Holiday,Abdel Nader,Al Horford,Al-Farouq Aminu,Alan Williams,Alec Burks,Alex Abrines,Alex Caruso,Alex Len,...,Wilson Chandler,Yante Maten,Yogi Ferrell,Yuta Watanabe,Zach Collins,Zach LaVine,Zach Lofton,Zaza Pachulia,Zhaire Smith,Zhou Qi
TEAM_ABBREVIATION,,,,,,,,,,,,,,,,,,,,,
ATL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,77.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BKN,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BOS,0.0,0.0,0.0,68.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CHA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CHI,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,63.0,0.0,0.0,0.0,0.0
CLE,0.0,0.0,0.0,0.0,0.0,0.0,34.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DAL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DEN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DET,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,68.0,0.0,0.0
GSW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
HOU,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
IND,0.0,50.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
MEM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0
MIA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
MIL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
MIN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
NOP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
NYK,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
OKC,0.0,0.0,61.0,0.0,0.0,0.0,0.0,31.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ORL,78.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
PHI,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0
PHX,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
POR,0.0,0.0,0.0,0.0,81.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,77.0,0.0,0.0,0.0,0.0,0.0
SAC,0.0,0.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,...,0.0,0.0,71.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SAS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TOR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
UTA,0.0,0.0,0.0,0.0,0.0,0.0,17.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
WAS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [298]:
# Warren's code
g3_df = df.groupby('TEAM_ABBREVIATION')['DISPLAY_FIRST_LAST'].value_counts().unstack().fillna(0).astype(bool).sum()
g3_df[g3_df>1].max()

3

## 7:

Find the player who scored the least amount of points while playing in at least 40 games last season.

In [309]:
import numpy as np
# Sean's code
test = df.groupby('DISPLAY_FIRST_LAST')['PTS'].apply(lambda x:  pd.Series(np.where(len(x)>40,int(x.sum()),np.NaN)))

In [311]:
test.reset_index(level=1, drop=True).dropna().sort_values()

DISPLAY_FIRST_LAST
Sindarius Thornwell          62.0
Khyri Thomas                  nan
Jose Calderon               113.0
Kevin Love                    nan
Quincy Pondexter             98.0
Svi Mykhailiuk              133.0
Kyle O'Quinn                156.0
Jon Leuer                   156.0
Kenneth Faried                nan
Nene                        151.0
Kosta Koufos                156.0
Tyson Chandler              173.0
Justin Anderson             178.0
Semi Ojeleye                186.0
Lance Thomas                205.0
Moritz Wagner               207.0
Jordan Bell                 223.0
TJ Leaf                     225.0
Patrick Patterson           229.0
Keita Bates-Diop              nan
Ryan Broekhoff              167.0
Marquese Chriss             182.0
Thabo Sefolosha             190.0
Jonah Bolden                207.0
Kalin Lucas                   nan
Solomon Hill                191.0
Tyrone Wallace              218.0
Timothe Luwawu-Cabarrot     231.0
Khem Birch                  240.0
Zaza Pachulia               267.0
                            ...
JJ Redick                  1372.0
JR Smith                      nan
JaKarr Sampson                nan
Jaylen Brown                964.0
CJ McCollum                1468.0
Jacob Evans                   nan
Bryn Forbes                 967.0
Bogdan Bogdanovic           990.0
Cedi Osman                  991.0
Jayson Tatum               1243.0
Ben Simmons                1337.0
Jamal Murray               1367.0
Collin Sexton              1371.0
De'Aaron Fox               1399.0
Bojan Bogdanovic           1454.0
DeMar DeRozan              1635.0
Buddy Hield                1695.0
Damian Lillard             2067.0
J.J. Barea                    nan
Isaiah Thomas                 nan
Isaiah Hicks                  nan
D'Angelo Russell           1712.0
Bradley Beal               2099.0
James Harden               2818.0
Isaiah Hartenstein            nan
Isaiah Canaan                 nan
Blake Griffin              1841.0
Isaiah Briscoe                nan
J.P. Macura                   nan
Zhou Qi                       nan
Name: PTS, Length: 530, dtype: object

In [310]:
test # pd.series with mult-level index

DISPLAY_FIRST_LAST
Aaron Gordon         0    1246.0
Aaron Holiday        0     294.0
Abdel Nader          0     241.0
Al Horford           0     925.0
Al-Farouq Aminu      0     760.0
Alan Williams        0       nan
Alec Burks           0     561.0
Alex Abrines         0       nan
Alex Caruso          0       nan
Alex Len             0     854.0
Alex Poythress       0       nan
Alfonzo McKinnie     0     337.0
Alize Johnson        0       nan
Allen Crabbe         0     413.0
Allonzo Trier        0     695.0
Amile Jefferson      0       nan
Amir Johnson         0     201.0
Andre Drummond       0    1370.0
Andre Iguodala       0     389.0
Andre Ingram         0       nan
Andrew Bogut         0       nan
Andrew Harrison      0       nan
Andrew Wiggins       0    1321.0
Anfernee Simons      0       nan
Angel Delgado        0       nan
Ante Zizic           0     459.0
Anthony Davis        0    1452.0
Anthony Tolliver     0     326.0
Antonio Blakeney     0     418.0
Aron Baynes          0     284.0
                           ...
Tyler Zeller         0       nan
Tyreke Evans         0     706.0
Tyrone Wallace       0     218.0
Tyson Chandler       0     173.0
Tyus Jones           0     468.0
Udonis Haslem        0       nan
Victor Oladipo       0       nan
Vince Carter         0     562.0
Vincent Edwards      0       nan
Wade Baldwin IV      0       nan
Walter Lemon Jr.     0       nan
Wayne Ellington      0     545.0
Wayne Selden         0     514.0
Wendell Carter Jr.   0     455.0
Wes Iwundu           0     339.0
Wesley Johnson       0       nan
Wesley Matthews      0     840.0
Will Barton          0     494.0
Willie Cauley-Stein  0     965.0
Willy Hernangomez    0     421.0
Wilson Chandler      0     305.0
Yante Maten          0       nan
Yogi Ferrell         0     420.0
Yuta Watanabe        0       nan
Zach Collins         0     512.0
Zach LaVine          0    1492.0
Zach Lofton          0       nan
Zaza Pachulia        0     267.0
Zhaire Smith         0       nan
Zhou Qi              0       nan
Name: PTS, Length: 530, dtype: object

In [307]:
# Gal's code
players = df.groupby(['DISPLAY_FIRST_LAST']).agg({'DISPLAY_FIRST_LAST': 'count', 'PTS': 'sum'})
psble_players = players.loc[players.DISPLAY_FIRST_LAST > 40]
worse_player = psble_players.loc[psble_players.PTS == psble_players.PTS.min()]
worse_player

                     DISPLAY_FIRST_LAST  PTS
DISPLAY_FIRST_LAST
Sindarius Thornwell                  64   62

In [ ]:

conditions = [
    (df['DISPLAY_FIRST_LAST'].count > 40) & (df['Type'] == 'A'),
    (df['Set'] == 'Z') & (df['Type'] == 'B'),
    (df['Type'] == 'B')]
choices = ['yellow', 'blue', 'purple']
df['color'] = np.select(conditions, choices, default='black')
print(df)

In [ ]:
df.DISPLAY_FIRST_LAST.

In [ ]:
df.groupby('A').B.agg(['min', 'max'])

In [257]:
# df['PTS'].idxmax(axis = 0)
print(df.DISPLAY_FIRST_LAST.groupby('DISPLAY_FIRST_LAST').[[df['PTS']==df['PTS'].min()]count() > 40], '\n')

SyntaxError: invalid syntax (<ipython-input-257-a0dcf5f60b42>, line 2)

# Part 4: Pandas and Probability

## 8: 

What is the probability that a random player had a game where they scored more than 40 points?

In [312]:
# Sean's code
len(df[df.PTS >= 40])/len(df)

0.005248841040573158

## 9:

What is the probability that a randomly selected player from last season would average more than 20 points per game?

In [315]:
# Sean's code
player_grouped = df.groupby['DISPLAY_FIRST_LAST']
np.sum(player_grouped['PTS'].mean()>20)/530

TypeError: 'method' object is not subscriptable

In [ ]:
# Rafi's code
import statistics

def group_players(df):
    return df.groupby(['DISPLAY_FIRST_LAST'])

#retrieve total number of unique players
def total_players(df):
    grouped_players = group_players(df)
    return len(grouped_players)
#calculate odds of getting num1 in sample space num2
def calculate_odds(num1, num2):
    return (num1/num2)

#return a DF of all the games featuring players who have scored over 20
def attribute_over_20(df, attribute):
    grouped_players = group_players(df)
    #filter by selecting where mean of attribute is greater than 20
    over_20_avg = grouped_players.filter(lambda x : statistics.mean(x[attribute]) > 20)
    return over_20_avg
def num_of_20_ppg(df):
    #get data_frame of all games with players who have 20 or better average
    players_over_20 = attribute_over_20(df, 'PTS')
    grouped_players = group_players(players_over_20)
    #regroup and get the length to get count
    num_of_players = len(grouped_players)
    return num_of_players
#probability of getting a player with 20 plus ppg average at random
def probs_of_20_avg(df):
    players_total = total_players(df)
    over_20_ppg_players = num_of_20_ppg(df)
    return calculate_odds(over_20_ppg_players, players_total)

# Advanced Questions

## 10: 
Find the player who scored the least amount of points while playing in at least 40 games and averageing at least 15 minutes per game last season.

In [ ]:
player_grouped.aggregate({'Player_ID >= 40 & MIN >= 15'})['PTS']

## 11: 
Which player scored the largest share of points for their team throughout the season.

In [ ]:
#your code here

## 12:

What is the probability that a randomly selected player had at least one game in which they scored at least 40 points last season.

In [316]:
# your code here
len(df.loc[df['PTS']>=40]['DISPLAY_FIRST_LAST'].unique())/len(df['DISPLAY_FIRST_LAST'].unique())

0.06981132075471698

## 13: 

A double-double is when a player records double digits for any of the two follow categories: points, rebounds, assists, steals, or blocks. 
What is the probability that a randomly selected player had a double-double in a game last season?

In [ ]:
#your code here

## 14:

What is the probability that a randomnly selected game had a player record a triple-double in that game?

In [ ]:
#your code here

# Part 5: Super Duper Challenge

## 15:

How many players last season averaged more points per game than their career average?